mqtt:
 client:
  protocol: 4
 connection:
  host: 192.168.1.22
  port: 1883
  keepalive: 60
 private_path: robot
       

bridge:
# TOPIC: move_base_simple/goal - TYPE: geometry_msgs/PoseStamped
- factory: mqtt_bridge.bridge:RosToMqttBridge 
  msg_type: geometry_msgs.msg:PoseStamped
  topic_from: /move_base_simple/goal
  topic_to: ~/fromGoal
- factory: mqtt_bridge.bridge:MqttToRosBridge
  msg_type: geometry_msgs.msg:PoseStamped
  topic_from: ~/toGoal
  topic_to: /move_base_simple/goal

# TOPIC: /Buzzer - TYPE: std_msgs/Bool
- factory: mqtt_bridge.bridge:RosToMqttBridge 
  msg_type: std_msgs.msg:Bool
  topic_from: /Buzzer
  topic_to: ~/fromBuzzer 
- factory: mqtt_bridge.bridge:MqttToRosBridge
  msg_type: std_msgs.msg:Bool
  topic_from: ~/toBuzzer
  topic_to: /Buzzer

# TOPIC: /cmd_vel - TYPE: geometry_msgs/Twist
- factory: mqtt_bridge.bridge:RosToMqttBridge
  msg_type: geometry_msgs.msg:Twist
  topic_from: /cmd_vel
  topic_to: ~/fromCmdVel 
- factory: mqtt_bridge.bridge:MqttToRosBridge
  msg_type: geometry_msgs.msg:Twist
  topic_from: ~/toCmdVel 
  topic_to: /cmd_vel

# TOPIC: /vel_raw - TYPE: geometry_msgs/Twist 
- factory: mqtt_bridge.bridge:RosToMqttBridge
  msg_type: geometry_msgs.msg:Twist
  topic_from: /vel_raw
  topic_to: ~/fromVelRaw
- factory: mqtt_bridge.bridge:MqttToRosBridge
  msg_type: geometry_msgs.msg:Twist
  topic_from: ~/toVelRaw 
  topic_to: /vel_raw


  # TOPIC: /voltage - TYPE: geometry_msgs/Twist 
- factory: mqtt_bridge.bridge:RosToMqttBridge
  msg_type: std_msgs.msg:Float32
  topic_from: /voltage
  topic_to: ~/voltageToMqtt
- factory: mqtt_bridge.bridge:MqttToRosBridge
  msg_type: std_msgs.msg:Float32
  topic_from: ~/voltageFromMqtt  
  topic_to: /voltage

  # TOPIC: /move_base/status - TYPE: actionlib_msgs/GoalStatusArray
- factory: mqtt_bridge.bridge:RosToMqttBridge
  msg_type: actionlib_msgs/GoalStatusArray
  topic_from: /move_base/status
  topic_to: ~/fromStatus
- factory: mqtt_bridge.bridge:MqttToRosBridge
  msg_type: actionlib_msgs/GoalStatusArray
  topic_from: ~/toStatus  
  topic_to: /move_base/status

##################################################

# Bool Data Communication
- factory: mqtt_bridge.bridge:RosToMqttBridge
  msg_type: std_msgs.msg:Bool
  topic_from: /robot/boolToMqtt
  topic_to: ~/boolToMqtt
- factory: mqtt_bridge.bridge:MqttToRosBridge
  msg_type: std_msgs.msg:Bool
  topic_from: ~/boolToRos
  topic_to: /robot/boolToRos

#Signed Int List Communication Using Custom msg Type
- factory: mqtt_bridge.bridge:RosToMqttBridge
  msg_type: mqtt_bridge.msg:IntList 
  topic_from: /robot/intListToMqtt
  topic_to: ~/intListToMqtt
- factory: mqtt_bridge.bridge:MqttToRosBridge
  msg_type: mqtt_bridge.msg:IntList
  topic_from: ~/intListToRos
  topic_to: /robot/intListToRos
